### ISSUE TITLE
Possible issue with sampling a vector of multinomials

### ISSUE THREAD

**Issue by ColinMcAuliffe** [pymc-devs/pymc#2550]
I'm making a model using softmax regression for choices among options A, B, and C. There are 6 groups, and I'm interested in how decisions differ among those groups, so I have a multinomial distribution for each group. Inference seems to work fine, but there is an error when sampling the posterior. I think it could have something to do with the fact that I have a vector of multinomials rather than a single one. The full error message and code to reproduce are below. Thanks!
```python
import numpy as np
import pandas as pd
import pymc3 as pm
import matplotlib.pyplot as plt
import seaborn as sns
sns.set(color_codes=True)

import theano

from scipy.stats import norm

def hierarchical_normal(name, shape, mu=0.,cs=5.):
    delta = pm.Normal('delta_{}'.format(name), 0., 1., shape=shape)
    sigma = pm.HalfCauchy('sigma_{}'.format(name), cs)
    
    return pm.Deterministic(name, mu + delta * sigma)

NUTS_KWARGS = {'target_accept': 0.99}
SEED = 4260026 # from random.org, for reproducibility

np.random.seed(SEED)

ndraws = 1000

counts =[[19, 50, 37],
         [21, 67, 55],
         [11, 53, 38],
         [17, 54, 45],
         [24, 93, 66],
         [27, 53, 70]]

counts = pd.DataFrame(counts,columns=["A","B","C"])

counts["n"]    = counts[["A","B","C"]].sum(axis=1)
print counts

group   = counts.index.values
n_group = np.unique(group).size

obs_n    = np.reshape(counts.n.values,(6,1))

obs_n_ = theano.shared(obs_n)

obs_ABC = counts[["A","B","C"]].values
with pm.Model() as model:
    #Zeros for coefficients for A
    ref = pm.Flat("ref",shape=n_group)

    #For B
    beta0      = pm.Normal('beta0', 0.,sd=5.)
    beta_group = hierarchical_normal('beta_group', n_group)
    

    #For C
    #alpha0      = pm.Normal('alpha0', 0.,sd=5.)
    alpha_group = hierarchical_normal('alpha_group', n_group)

    eta_B   = beta0  + beta_group [group]
    #eta_C   = alpha0 + alpha_group[group]
    eta_C   = alpha_group[group]
    p = theano.tensor.nnet.softmax(theano.tensor.stack(ref,eta_B,eta_C).T)
    like = pm.Multinomial('obs_ABC', obs_n, p, observed=obs_ABC)

    trace  = pm.sample(draws=ndraws, random_seed=SEED,nuts_kwargs=NUTS_KWARGS)

plt.figure()
axs = pm.forestplot(trace,varnames=['beta0','beta_group','alpha_group'])
plt.savefig("Forest.png")
plt.close()

plt.figure()
axs = pm.traceplot(trace,varnames=['beta0','beta_group','alpha_group'])
plt.savefig("Trace.png")
plt.close()

obs_n_.set_value(np.reshape(np.array([10000]*6),(6,1)))
pp_trace = pm.sample_ppc(trace, model=model)

with open('softmax_PP.pkl', 'wb') as buff:
    pickle.dump(pp_trace, buff)

with open('softmax_PP.pkl', 'rb') as buff:
    pp_trace = pickle.load(buff)  

print pp_trace["obs_ABC"]



_________________________________________________________________________________

    A   B   C    n
0  19  50  37  106
1  21  67  55  143
2  11  53  38  102
3  17  54  45  116
4  24  93  66  183
5  27  53  70  150
Auto-assigning NUTS sampler...
Initializing NUTS using ADVI...
Average Loss = 49.994:  12%|█████████▍                                                                        | 23062/200000 [00:04<00:36, 4843.61it/s]
Convergence archived at 23500
Interrupted at 23,500 [11%]: Average Loss = 195
100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1500/1500 [00:18<00:00, 81.01it/s]
/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/matplotlib/tight_layout.py:222: UserWarning: tight_layout : falling back to Agg renderer
  warnings.warn("tight_layout : falling back to Agg renderer")
  0%|                                                                                                                         | 0/1000 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "softmax.py", line 77, in <module>
    pp_trace = pm.sample_ppc(trace, model=model)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pymc3/sampling.py", line 539, in sample_ppc
    vals = var.distribution.random(point=param, size=size)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pymc3/distributions/multivariate.py", line 506, in random
    size=size)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pymc3/distributions/distribution.py", line 397, in generate_samples
    *args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pymc3/distributions/distribution.py", line 322, in replicate_samples
    samples = generator(size=size, *args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pymc3/distributions/multivariate.py", line 500, in _random
    return np.random.multinomial(n, p, size=size)
  File "mtrand.pyx", line 4530, in mtrand.RandomState.multinomial (numpy/random/mtrand/mtrand.c:37665)
TypeError: only length-1 arrays can be converted to Python scalars

```

**Comment by aseyboldt** [comment]
I think this might have been fixed in #2432 already. Could you update to master and try again?

**Comment by ColinMcAuliffe** [comment]
I updated with 

pip install git+https://github.com/pymc-devs/pymc3

but the error remains. Could it have something to do with the fact that obs_n is a (6,1) array rather than a (6,) array? I had to define it as (6,1) because (6,) caused an error in the model definition.

  File "softmax.py", line 77, in <module>
    pp_trace = pm.sample_ppc(trace, model=model)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pymc3/sampling.py", line 573, in sample_ppc
    size=size))
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pymc3/distributions/multivariate.py", line 527, in random
    size=size)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pymc3/distributions/distribution.py", line 412, in generate_samples
    *args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pymc3/distributions/distribution.py", line 337, in replicate_samples
    samples = generator(size=size, *args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pymc3/distributions/multivariate.py", line 517, in _random
    randnum = np.asarray([np.random.multinomial(n, pp, size=size) for pp in p])
  File "mtrand.pyx", line 4530, in mtrand.RandomState.multinomial (numpy/random/mtrand/mtrand.c:37665)
TypeError: only length-1 arrays can be converted to Python scalars

**Comment by junpenglao** [comment]
I am on master and you model can sample without problem, could you please try 
`pip install --upgrade git+https://github.com/pymc-devs/pymc3`?

**Comment by ColinMcAuliffe** [comment]
No luck, here is the output from the pip command in case that's useful somehow

Collecting git+https://github.com/pymc-devs/pymc3
  Cloning https://github.com/pymc-devs/pymc3 to /private/tmp/pip-nJo9Pn-build
Requirement already up-to-date: matplotlib>=1.5.0 in /Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages (from pymc3==3.1)
Requirement already up-to-date: theano>=0.9.0 in /Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages (from pymc3==3.1)
Requirement already up-to-date: pandas>=0.18.0 in /Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages (from pymc3==3.1)
Requirement already up-to-date: patsy>=0.4.0 in /Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages (from pymc3==3.1)
Requirement already up-to-date: joblib>=0.9 in /Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages (from pymc3==3.1)
Requirement already up-to-date: tqdm>=4.8.4 in /Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages (from pymc3==3.1)
Requirement already up-to-date: six>=1.10.0 in /Library/Python/2.7/site-packages/six-1.10.0-py2.7.egg (from pymc3==3.1)
Requirement already up-to-date: h5py>=2.7.0 in /Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages (from pymc3==3.1)
Requirement already up-to-date: enum34>=1.1.6; python_version < "3.4" in /Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages (from pymc3==3.1)
Requirement already up-to-date: python-dateutil in /Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages (from matplotlib>=1.5.0->pymc3==3.1)
Requirement already up-to-date: subprocess32 in /Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages (from matplotlib>=1.5.0->pymc3==3.1)
Requirement already up-to-date: cycler>=0.10 in /Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages (from matplotlib>=1.5.0->pymc3==3.1)
Requirement already up-to-date: pytz in /Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages (from matplotlib>=1.5.0->pymc3==3.1)
Requirement already up-to-date: functools32 in /Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages (from matplotlib>=1.5.0->pymc3==3.1)
Requirement already up-to-date: numpy>=1.7.1 in /Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages (from matplotlib>=1.5.0->pymc3==3.1)
Requirement already up-to-date: pyparsing!=2.0.4,!=2.1.2,!=2.1.6,>=1.5.6 in /Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages (from matplotlib>=1.5.0->pymc3==3.1)
Requirement already up-to-date: scipy>=0.14 in /Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages (from theano>=0.9.0->pymc3==3.1)
Installing collected packages: pymc3
  Found existing installation: pymc3 3.1
    Uninstalling pymc3-3.1:
      Successfully uninstalled pymc3-3.1
  Running setup.py install for pymc3 ... done
Successfully installed pymc3-3.1

**Comment by ColinMcAuliffe** [comment]
The numpy version might alse be relevant

>>> numpy.__version__
'1.13.1'

I've noticed that since I upgraded to this version, I've gotten a few strange indexing errors in various packages.

**Comment by ColinMcAuliffe** [comment]
I've tried a whole bunch of different numpy versions with no luck. I assume though that this is something to do with my local installation since the script I wrote apparently worked for @junpenglao 

Any ideas of where to look next?

**Comment by ColCarroll** [comment]
I can recreate, in python2 and python3 -- checking on it now...

**Comment by ColCarroll** [comment]
So #2430 fixed this for `p` with higher dimensions, but there's no support in `numpy` or `scipy` for doing this with `n` in higher dimensions, which happens here.  A smaller example to reproduce the problem is:

```
n = np.array([[106],
 [143],
 [102],
 [116],
 [183],
 [150]])

p = np.array([[ 0.21245365,  0.41223126,  0.37531509],
 [ 0.13221011,  0.50537169,  0.3624182 ],
 [ 0.08813779,  0.54447146,  0.36739075],
 [ 0.18932804,  0.4630365,   0.34763546],
 [ 0.11006472,  0.49227755,  0.39765773],
 [ 0.17886852,  0.41098834, 0.41014314]])

np.random.multinomial(n, p, size=None)
```
Note that currently in the code, we are actually calling

```
[np.random.multinomial(n, pp, size=None) for pp in p]
```
but I think the intention is as in the first example.

**Comment by junpenglao** [comment]
You guys are right - I didnt pay attention to the error message (it's `sample_ppc`). I will send a fix.

**Comment by ColinMcAuliffe** [comment]
This looks like it should work, is it going to get merged into master?

**Comment by junpenglao** [comment]
Almost - I am waiting for https://github.com/pymc-devs/pymc3/pull/2540 to merge first.

**Comment by junpenglao** [comment]
Fixed in #2555
