### ISSUE TITLE
observed_data missing from InferenceData when data is cast

### ISSUE THREAD

**Issue by ricardoV94** [pymc-devs/pymc#5586]
A user on discourse reported that `observed_data` is missing from the InferenceData returned from the jax samplers in `sampling_jax.py`. We should check if that is still the case and fix it.

https://discourse.pymc.io/t/pymc-v4-not-returning-observed-data-in-inferencedata-object/8916

**Comment by zaxtax** [comment]
I just did a cursory check and `observed_data` is in the `InferenceData` object returned. Happy to add a unit test for this, but more interested in reproducing the user's error.

**Comment by fbarfi** [comment]
Have been using sampling_jax with no problem -- observed_data always in inference data object.

**Comment by ricardoV94** [comment]
Thanks @zaxtax and @fbarfi

I'll close the issue as it seems it was already solved

**Comment by vethno** [comment]
I apologize for the delay in uploading the minimal example to PyMC Discourse. I am still having the issue.

https://discourse.pymc.io/t/pymc-v4-not-returning-observed-data-in-inferencedata-object/8916/3

Per the post, it works with some distributions, but when I use a mixture distribution like `pm.NegativeBinomial()` or `pm.ZeroInflatedNegativeBinomial()`

**Comment by zaxtax** [comment]
Yep, I am able to reproduce this. Looking into it now.

**Comment by zaxtax** [comment]
The problem actually shows up if you use regular `pm.sample` so it's likely something on the distribution as @OriolAbril suggested.

**Comment by zaxtax** [comment]
It seems to be related to an interaction between `pm.Data` and `pm.NegativeBinomial`

The following contains `observed_data`:

````python
with pm.Model() as model:
     t = pm.Gamma("t", 1, 1)
     y = pm.NegativeBinomial('y', mu=t, alpha=0.5, observed=5)
     trace = pm.sample(tune=20, draws=40)
````

While this does not:

````python
with pm.Model() as model:
     c = pm.Data("c", 5)
     t = pm.Gamma("t", 1, 1)
     y = pm.NegativeBinomial('y', mu=t, alpha=0.5, observed=c)
     trace = pm.sample(tune=20, draws=40)
````

**Comment by ricardoV94** [comment]
Does that problem with `pm.Data`, happen with other distributions?

**Comment by zaxtax** [comment]
@ricardoV94 yep. I have replicated it with other discrete distributions like `Bernoulli` and `Binomial`

**Comment by ricardoV94** [comment]
Does it happen with continuous distributions? Might be that the data is being casted to discrete and that's why the InferenceData converter cannot see it.

**Comment by zaxtax** [comment]
I've possibly narrowed it down to https://github.com/pymc-devs/pymc/blob/main/pymc/aesaraf.py#L234 in the `extract_obs_data` function. If that `isinstance` check is removed it works. Maybe this is something @brandonwillard has insights on?

**Comment by zaxtax** [comment]
> Does it happen with continuous distributions? Might be that the data is being casted to discrete and that's why the InferenceData converter cannot see it.

I have no problems using continuous distributions but I haven't tested all of them.

**Comment by ricardoV94** [comment]
Yeah, the problem is the cast:

```python
import pymc as pm
with pm.Model() as model:

    c = pm.Data("c", 5)
    y = pm.Bernoulli('y', p=0.5, observed=c)

print(model.rvs_to_values[y].owner)  # Elemwise{Cast{int64}}(c)
```

In that function we need a branch for the case where the data is casted to another dtype.

**Comment by ricardoV94** [comment]
Closed via #5646
