### ISSUE TITLE
"semi-hierarchical" model (Too many parameter passed to theano function)

### ISSUE THREAD

**Issue by aloctavodia** [pymc-devs/pymc#580]
I want to write a model, like the one below. The main idea is that I have several conditions (or treatments) all parameters are estimated for each condition independently, except the kappa parameter that is the same for all conditions. 

``` python
with pm.Model() as model:
    trace_per_condition = []
    # define the kappa hyperparameter
    kappa = pm.Gamma('kappa', 1, 0.1)
    for condition in range(0, ncond):
        z_cond = z[condition]
        # define the mu hyperparameter
        mu = pm.Beta('mu_%i' % condition, 1, 1)
        # define the prior
        theta = pm.Beta('theta_%i' % condition, mu * kappa, (1 - mu) * kappa, shape=len(z_cond))
        # define the likelihood
        y = pm.Binomial('y_%i' % condition, p=theta, n=trials, observed=z_cond)
        # Generate a MCMC chain
        start = pm.find_MAP()
        step1 = pm.Metropolis([theta, mu])
        step2 = pm.NUTS([kappa])
        trace = pm.sample(10000, [step1, step2], start=start, progressbar=False)
        trace_per_condition.append(trace)
```

I get the following warnings:

``` python
/usr/local/lib/python2.7/dist-packages/Theano-0.6.0-py2.7.egg/theano/gradient.py:513: 
UserWarning: grad method was asked to compute the gradient with respect to a variable that 
is not part of the computational graph of the cost, or is used only by a non-differentiable 
operator: mu_1 handle_disconnected(elem)
/usr/local/lib/python2.7/dist-packages/Theano-0.6.0-py2.7.egg/theano/gradient.py:533: 
UserWarning: grad method was asked to compute the gradient with respect to a variable that 
is not part of the computational graph of the cost, or is used only by a non-differentiable 
operator: <DisconnectedType>handle_disconnected(rval[i])
/usr/local/lib/python2.7/dist-packages/Theano-0.6.0-py2.7.egg/theano/gradient.py:513: 
UserWarning: grad method was asked to compute the gradient with respect to a variable that 
is not part of the computational graph of the cost, or is used only by a non-differentiable 
operator: theta_1 handle_disconnected(elem)
```

And also the following error:

``` python
Traceback (most recent call last):
  File "<stdin>", line 43, in <module>
  File "/usr/local/lib/python2.7/dist-packages/pymc-3.0-py2.7.egg/pymc/tuning/starting.py", line 80, in find_MAP
    start), fprime=grad_logp_o, disp=disp, *args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/scipy/optimize/optimize.py", line 777, in fmin_bfgs
    res = _minimize_bfgs(f, x0, args, fprime, callback=callback, **opts)
  File "/usr/lib/python2.7/dist-packages/scipy/optimize/optimize.py", line 837, in _minimize_bfgs
    old_fval = f(x0)
  File "/usr/lib/python2.7/dist-packages/scipy/optimize/optimize.py", line 281, in function_wrapper
    return function(*(wrapper_args + args))
  File "/usr/local/lib/python2.7/dist-packages/pymc-3.0-py2.7.egg/pymc/tuning/starting.py", line 72, in logp_o
    return nan_to_high(-logp(point))
  File "/usr/local/lib/python2.7/dist-packages/pymc-3.0-py2.7.egg/pymc/blocking.py", line 119, in __call__
    return self.fa(self.fb(x))
  File "/usr/local/lib/python2.7/dist-packages/pymc-3.0-py2.7.egg/pymc/model.py", line 283, in __call__
    return self.f(**state)
  File "/usr/local/lib/python2.7/dist-packages/Theano-0.6.0-py2.7.egg/theano/compile/function_module.py", line 482, in __call__
    raise TypeError("Too many parameter passed to theano function")
TypeError: Too many parameter passed to theano function
```

I have also asked this on SO http://stackoverflow.com/questions/24945018/how-to-define-a-model-in-pymc3-with-one-parameter-constrained-to-the-same-value

**Comment by aloctavodia** [comment]
@jsalvatier suggest me on SO, to do something like:

``` python
ncond = 4
nSubj = 40
trials = 64

N= np.repeat([trials], (ncond * nSubj))
z = np.array([45, 63, 58, 64, 58, 63, 51, 60, 59, 47, 63, 61, 60, 51, 59, 45,
61, 59, 60, 58, 63, 56, 63, 64, 64, 60, 64, 62, 49, 64, 64, 58, 64, 52, 64, 64,
64, 62, 64, 61, 59, 59, 55, 62, 51, 58, 55, 54, 59, 57, 58, 60, 54, 42, 59, 57,
59, 53, 53, 42, 59, 57, 29, 36, 51, 64, 60, 54, 54, 38, 61, 60, 61, 60, 62, 55,
38, 43, 58, 60, 44, 44, 32, 56, 43, 36, 38, 48, 32, 40, 40, 34, 45, 42, 41, 32,
48, 36, 29, 37, 53, 55, 50, 47, 46, 44, 50, 56, 58, 42, 58, 54, 57, 54, 51, 49,
52, 51, 49, 51, 46, 46, 42, 49, 46, 56, 42, 53, 55, 51, 55, 49, 53, 55, 40, 46,
56, 47, 54, 54, 42, 34, 35, 41, 48, 46, 39, 55, 30, 49, 27, 51, 41, 36, 45, 41,
53, 32, 43, 33])
condition = np.repeat([0,1,2,3], nSubj)

with pm.Model() as model:
    kappa = pm.Gamma('kappa', 1, 0.1)
    mu = pm.Beta('mu', 1, 1, shape=ncond)
    theta = pm.Beta('theta', mu[condition] * kappa, (1 - mu[condition]) * kappa, shape=len(z))
    y = pm.Binomial('y', p=theta, n=N, observed=z)
    start = pm.find_MAP()
    step1 = pm.Metropolis([theta, mu])
    step2 = pm.NUTS([kappa])
    trace = pm.sample(10000, [step1, step2], start=start, progressbar=False)
```

Nevertheless, in this model the variables are not independent. I am trying to implement a model where the mu, theta and y on one condition does not talk to the mu, theta and y of the other conditions.

**Comment by jsalvatier** [comment]
I think this model has that property. They only talk through kappa. Each
observation uses the mu for its condition and theta is different for each
observation.

**Comment by aloctavodia** [comment]
I am not familiar with the PyMC implementation (as you should have noticed). But I am still thinking that in the model you proposed the variables are not independent across conditions. Let me explain why I think so:

1) I am reading the book "Doing Bayesian Data Analysis" and I am "translating" the examples from R/BUGS to Python/PyMC. If I use the model as you propose I am not able to reproduce the corresponding figure in the book. 

2) If I understood correctly the examples [here](http://twiecki.github.io/blog/2014/03/17/bayesian-glms-3/). what you proposed is equivalent to the Hierarchical Model, while what I am trying to do is "in the middle" of the Hierarchical model and the non-hierarchical model.

3) For a closely related example I have [uploaded](https://github.com/aloctavodia/Doing_bayesian_data_analysis) two alternative models see 09_FilconPyMC.py and 09_FilconPyMCb.py, the first one produce a plot that is closer to the one in the book than the second model (see also Figure_9.16.png and Figure_9.16b.png). Leaving aside comparisons with book, both model are not equivalent and they do not give similar results (or I am making some mistake).

**Comment by kyleam** [comment]
> But I am still thinking that in the model you proposed the variables are not independent across conditions.

In the above model, the values of `mu` are independent, while a single `kappa` is shared. 

> what you proposed is equivalent to the Hierarchical Model, while what I am trying to do is "in the middle" of the Hierarchical model and the non-hierarchical model

I don't see anything hierarchical here (the hyperparameters for `mu` are fixed).

**Comment by aloctavodia** [comment]
Is hierarchical because the hyperparameters, mu and kappa are not fixed and those are the parameters for theta (the prior). 
Clearly I am missing something important here. I will check again the examples 09_FilconPyMC.py and 09_FilconPyMCb.py and try to understand what I am missing. 

Thanks for your answers!

**Comment by aloctavodia** [comment]
At the risk of became a pain in the ***. Could someone explain me the difference between these two models. I though I understood the difference, but according to your explanations both should be the same (one being the vectorized version of the other).

``` python
ncond = 4
nSubj = 40
trials = 64

z = np.array([45, 63, 58, 64, 58, 63, 51, 60, 59, 47, 63, 61, 60, 51, 59, 45,
61, 59, 60, 58, 63, 56, 63, 64, 64, 60, 64, 62, 49, 64, 64, 58, 64, 52, 64, 64,
64, 62, 64, 61, 59, 59, 55, 62, 51, 58, 55, 54, 59, 57, 58, 60, 54, 42, 59, 57,
59, 53, 53, 42, 59, 57, 29, 36, 51, 64, 60, 54, 54, 38, 61, 60, 61, 60, 62, 55,
38, 43, 58, 60, 44, 44, 32, 56, 43, 36, 38, 48, 32, 40, 40, 34, 45, 42, 41, 32,
48, 36, 29, 37, 53, 55, 50, 47, 46, 44, 50, 56, 58, 42, 58, 54, 57, 54, 51, 49,
52, 51, 49, 51, 46, 46, 42, 49, 46, 56, 42, 53, 55, 51, 55, 49, 53, 55, 40, 46,
56, 47, 54, 54, 42, 34, 35, 41, 48, 46, 39, 55, 30, 49, 27, 51, 41, 36, 45, 41,
53, 32, 43, 33]).reshape(ncond, nSubj)

trace_per_condition = []
for condition in range(0, ncond):
    z_cond = z[condition]
    with pm.Model() as model:
        mu = pm.Beta('mu', 1, 1)
        kappa = pm.Gamma('kappa', 1, 0.1)
        theta = pm.Beta('theta', mu * kappa, (1 - mu) * kappa, shape=len(z_cond))
        y = pm.Binomial('y', p=theta, n=trials, observed=z_cond)
        start = pm.find_MAP()
        step1 = pm.Metropolis([theta, mu])
        step2 = pm.NUTS([kappa])
        trace = pm.sample(1000, [step1, step2], start=start, progressbar=False, random_seed=123)
    trace_per_condition.append(trace)
```

``` python
ncond = 4
nSubj = 40
trials = 64

N = np.repeat([trials], (ncond * nSubj))
z = np.array([45, 63, 58, 64, 58, 63, 51, 60, 59, 47, 63, 61, 60, 51, 59, 45,
61, 59, 60, 58, 63, 56, 63, 64, 64, 60, 64, 62, 49, 64, 64, 58, 64, 52, 64, 64,
64, 62, 64, 61, 59, 59, 55, 62, 51, 58, 55, 54, 59, 57, 58, 60, 54, 42, 59, 57,
59, 53, 53, 42, 59, 57, 29, 36, 51, 64, 60, 54, 54, 38, 61, 60, 61, 60, 62, 55,
38, 43, 58, 60, 44, 44, 32, 56, 43, 36, 38, 48, 32, 40, 40, 34, 45, 42, 41, 32,
48, 36, 29, 37, 53, 55, 50, 47, 46, 44, 50, 56, 58, 42, 58, 54, 57, 54, 51, 49,
52, 51, 49, 51, 46, 46, 42, 49, 46, 56, 42, 53, 55, 51, 55, 49, 53, 55, 40, 46,
56, 47, 54, 54, 42, 34, 35, 41, 48, 46, 39, 55, 30, 49, 27, 51, 41, 36, 45, 41,
53, 32, 43, 33])
condition = np.repeat([0,1,2,3], nSubj)

with pm.Model() as model:
    kappa = pm.Gamma('kappa', 1, 0.1, shape=ncond)
    mu = pm.Beta('mu', 1, 1, shape=ncond)
    theta = pm.Beta('theta', mu[condition] * kappa[condition], (1 - mu[condition]) * kappa[condition], shape=len(z))
    y = pm.Binomial('y', p=theta, n=N, observed=z)
    start = pm.find_MAP()
    step1 = pm.Metropolis([theta, mu])
    step2 = pm.NUTS([kappa])
    trace = pm.sample(1000, [step1, step2], start=start, progressbar=False, random_seed=123)
```

**Comment by twiecki** [comment]
The first model just creates separate models for each part of the data and estimates them. The second one builds one large model for all conditions, but -- as far as I can see -- does not share any RVs between the conditions. So ultimately it's just estimating nconds separate models (as they aren't linked) in one go.

**Comment by aloctavodia** [comment]
Thank you. But why they give different results? Is just a sampling problem? The second model is harder to sample than the first? I have increased the number of steps and changed the samplers and I consistently obtain different results for each model.

For example see this statistics for the mu variables.

loop model
  Mean             SD               MC Error         95% HPD interval
  0.879            0.000            0.000            [0.878, 0.879]
  0.840            0.020            0.001            [0.803, 0.880]
  0.710            0.021            0.001            [0.667, 0.748]
  0.706            0.020            0.001            [0.666, 0.741]

vectorized model
  Mean             SD               MC Error         95% HPD interval
  0.925            0.012            0.001            [0.913, 0.948]
  0.781            0.010            0.001            [0.773, 0.800]
  0.670            0.011            0.001            [0.652, 0.695]
  0.688            0.010            0.001            [0.669, 0.704]

**Comment by twiecki** [comment]
Does convergence look OK? There could also still be a bug in the model spec.

Lastly, the samplers currently use block updating which means in a larger model, acceptance will be very low. You can just give each RV it's own sampler (e.g. `samplers = [pm.Slice(rv) for rv in model.RVs]` or something like that) and the sampling should work the same across both models.

**Comment by aloctavodia** [comment]
Yes, converge looks OK. Giving each RV it's own sampler makes the results closer too the ones in the book (and across both models). So I think at the bottom this issue and #569 are the same.

**Comment by twiecki** [comment]
I see. Yeah, we should really implement the non-blocked option.

**Comment by twiecki** [comment]
There's a PR for what we discussed here: https://github.com/pymc-devs/pymc/pull/587

**Comment by aloctavodia** [comment]
Nice! I would like to try it also with this [model](https://github.com/aloctavodia/Doing_bayesian_data_analysis/blob/master/10_FilconModelCompPyMC.py) that seems to have sampling problems

**Comment by twiecki** [comment]
I tried that model and the plot it creates looked reasonable. What's the specific problem you're having?

I saw though that you already applied separate samplers to each RV so this should be identical but you can just `pm.Metropolis(model.unobserved_RVs[1:])` directly.

**Comment by aloctavodia** [comment]
Yes, I know it should be identical, but probably more elegant :-). You are right the list comprehension is unnecessary! Thanks for pointing that out. 

The problem is that the plots looks reasonable, but I think they do not agree with the one in the book. ASAP I will re-check the model  (just to be sure I am doing the right thing). 
A minor thing. It took me some time to realize that I should use the ElemwiseCategoricalStep (I had not previous experience with this sampler). In the book Kruschke discus the idea of using pseudo-priors, but I think the use of ElemwiseCategoricalStep makes the use of pseudo-priors unnecessary.

**Comment by aloctavodia** [comment]
BTW, if i use pm.NUTS(model.unobserved_RVs[1:]), instead of pm.Metropolis(model.unobserved_RVs[1:])
The sampling takes a lot of time (indeed I did not have the patience t wait and I kill the process). This does not happens if NUTS is used for just a couple of variables.

**Comment by twiecki** [comment]
One issue I realized is the find_MAP(). This model is really odd as only half of the model is connected to output at any given time. Here is a procedure to find a starting point iteratively:

Note that I changed the order in the `switch`.

``` python
    theta = pm.switch(pm.eq(model_index, 0), theta0, theta1)

    # Likelihood:
    y = pm.Binomial('y', p=theta, n=n_trl_of_subj, observed=n_corr_of_subj)

    # Sampling
    model_index.tag.test_value = np.array([0])
    start0 = pm.find_MAP(vars=[kappa0, theta0])
    start0['model_index'] = np.array([1])
    start1 = pm.find_MAP(vars=[kappa1, theta1, mu], start=start0)
```

**Comment by twiecki** [comment]
I do see convergence problems where mu and theta1 never get updated.

**Comment by aloctavodia** [comment]
Did you compare this model with the one in the book?  Do you think the model must be rewritten to remove the oddness?

Note: The order in the switch was OK. I was trying to match the python code (that start counting at zero) with the one in the book (that start counting at 1). In the book, the second model (2) was the one with the kappa0 and the first model (1) the one with the four "kappa". But I think is a little confusing, I will fix that in the final version.

**Comment by twiecki** [comment]
Yes, quite some discrepancies as you noted. I think the main problem to attack is the lack of convergence on some nodes which seem to never have a proposed jump accepted. That's also why slice isn't working. So before recreating the plot from the book, I think the traces should look reasonable in `traceplot`.

I'm not sure yet what's causing this. Most likely model misspecification but it looks correct to me...

**Comment by aloctavodia** [comment]
The traces in my `traceplot` look reasonable (at least the values get updated).

``` python
with model:
    steps = [pm.Metropolis(model.unobserved_RVs[1:])]
    #steps.append(pm.NUTS([mu]))
    #steps.append(pm.NUTS([kappa0]))
    steps.append(pm.ElemwiseCategoricalStep(var=model_index,values=[0,1]))
    trace = pm.sample(10000, step=steps, progressbar=True)
```

![trace_plot](https://cloud.githubusercontent.com/assets/1338958/3955824/4ba16faa-2705-11e4-999f-3b179dbb60e8.png)

**Comment by twiecki** [comment]
Definitely. It's not what I saw but I probably messed up the model somehow. So not a convergence issue (or not an obvious one at least).
