### ISSUE TITLE
negative proposed values

### ISSUE THREAD

**Issue by nicoladimauro** [pymc-devs/pymc#649]
Dear all,
when in a model I have an array of Uniform distributions the Metropolis proposal outputs negative numbers raising ZeroProbability exception.

For instance having the following stochastic variable in the model 

xi = pymc.Uniform('xi', lower=0.0, upper=1.0, size = dataRows, verbose=5)

the sampler produces always the following ZeroProbability exception, probably due to the size of the array (dataRows=100 for instance)

How can I solve this problem? 

Metropolis_xi getting initial logp.
    xi: logp accessed.
    xi: Returning log-probability  0.0
    Metropolis_xi Current log-likelihood plus current log-probability -747.75176259
Metropolis_xi proposing.
    xi: value accessed.
    xi: value accessed.
    xi: value set to  [  5.46142563e-01   1.27285991e-01  -3.08915769e-02   2.12328077e+00
   6.70107737e-01   8.86281220e-01  -3.14646593e-03   1.06998464e-01
   1.15818217e-01   5.93383388e-01   4.88359946e-02   3.57460223e-01
   5.40658290e-01  -3.59732849e-04   7.50340428e-01   8.98592929e-01
   1.71283209e+00  -2.22605172e-01   3.48218214e-01   7.60327475e-01]
    xi: logp accessed.
    xi: value accessed.
    xi: Returning log-probability  -1.79769313486e+308
Metropolis_xi rejecting due to ZeroProbability.
Metropolis_xi returning.

**Comment by fonnesbeck** [comment]
Do you happen to have thinning set in your sampler? Also, which version of PyMC are you using?

**Comment by nicoladimauro** [comment]
I'm using the pymn 2.3.3

This is a reprodution of a simple example with the following code

import pymc
var = pymc.Uniform("var",lower=0,upper=1, size=10, verbose=5)
M = pymc.MCMC([var], verbose=5)
M.use_step_method(pymc.Metropolis, var)
M.sample(iter=1000, verbose=5)

As you can see just for the first proposal the values are out of the bounds 0 and 1

```
var: value set to  [ 0.4778701   0.5312034   0.26330291  0.1430953   0.02351509  0.48800469
```

  0.71843473  0.73738985  0.91114278  0.74240073]
    var: value accessed.
    var: value accessed.
    var: value accessed.
    var: value accessed.
    var: logp accessed.
    var: Returning log-probability  0.0
    var: value accessed.
    var: value accessed.
    var: value accessed.
    var: value accessed.
    var: value accessed.
    var: value accessed.
Using step method Metropolis. Stochastics: 
    var
    var: logp accessed.
    var: Returning log-probability  0.0
Assigning step method DrawFromPrior to stochastic var
    var: value accessed.

Burn-in interval complete
Step method Metropolis_var stepping

Metropolis_var getting initial logp.
    var: logp accessed.
    var: Returning log-probability  0.0
    Metropolis_var Current log-likelihood plus current log-probability 0.0
Metropolis_var proposing.
    var: value accessed.
    var: value accessed.
    var: value set to  [ 1.06521939  1.04701457  0.42605706 -0.0928898   0.00913117  0.61020686
  1.10746305  0.77345352  0.23936555  0.78812331]
    var: logp accessed.
    var: value accessed.
    var: Returning log-probability  -1.79769313486e+308
Metropolis_var rejecting due to ZeroProbability.
Metropolis_var returning.
Step method DrawFromPrior_var stepping
    var: shape accessed.
    var: shape accessed.
    var: value set to  [ 0.46217845  0.72209701  0.80178511  0.25462846  0.50508062  0.22855205
  0.85938939  0.8048936   0.85941147  0.14934296]
    var: logp accessed.
    var: value accessed.
    var: Returning log-probability  0.0
MCMC tallying.
    var: value accessed.
MCMC done tallying.
Step method Metropolis_var stepping

Metropolis_var getting initial logp.
    var: logp accessed.
    var: Returning log-probability  0.0
    Metropolis_var Current log-likelihood plus current log-probability 0.0
Metropolis_var proposing.
    var: value accessed.
    var: value accessed.
    var: value set to  [ 0.52496055 -0.28086017  0.75243653  0.02388308  0.50606461  0.19493772
 -0.01535139  1.70126151  0.50929829  0.2867684 ]
    var: logp accessed.
    var: value accessed.
    var: Returning log-probability  -1.79769313486e+308
Metropolis_var rejecting due to ZeroProbability.
Metropolis_var returning.

**Comment by fonnesbeck** [comment]
This problem should be fixed in 2.3.4. You can upgrade to the latest via pip:

```
 pip install -U git+git://github.com/pymc-devs/pymc.git@2.3 
```

**Comment by nicoladimauro** [comment]
The same problem persist even with an upgrade to 2.3.4

the following code 

import pymc
var = pymc.Uniform("var",lower=0,upper=1, size=10, verbose=5)
M = pymc.MCMC([var], verbose=5)
M.use_step_method(pymc.Metropolis, var)
M.sample(iter=1000, verbose=5)
print M.step_method_dict.values()[0][0].rejected

give me 996 over 1000 rejected sampling!

**Comment by fonnesbeck** [comment]
What are the estimates you are getting from this run?

```
var.summary()
```

Why are you forcing it to use a Metropolis sampler?

**Comment by fonnesbeck** [comment]
The rejection rate is not surprising, because you have not run the sampler long enough for the proposal distribution to adapt. If you need a higher acceptance rate right away, you can pass a lower initial proposal variance:

```
M.use_step_method(pymc.Metropolis, var, proposal_sd=0.05)
```

Why are you concerned about the proposal of negative values? The sampler will sort this out by adapting.

**Comment by fonnesbeck** [comment]
Did this fix the issue? Closing this, but if it needs to be reopened, please open over on the [PyMC 2 repo](https://github.com/pymc-devs/pymc).
