### ISSUE TITLE
Deprecate SumTo1 Transform

### ISSUE THREAD

**Issue by ricardoV94** [pymc-devs/pymc#7009]
### Description

This seems to be an old transform that was replaced by the Simplex transform.

**Comment by twiecki** [comment]
@PulsatingGenius Great, just open a PR (can be draft too).

**Comment by nyeshlur** [comment]
Hello if this issue is not currently being worked on I would like to work on it. I was wondering what needs to be included in a draft pull request?

**Comment by ricardoV94** [comment]
For now just a FutureWarning when users access the transform to let them know it's deprecated and will be removed in the future 

Plus a test that verified the warning is working but you can still access it

**Comment by nyeshlur** [comment]
Hi so I have created a FutureWarning in pymc/distributions/transforms.py and I have written a test in tests/distributions/test_transform.py. I'm not sure if this is what is needed and I'm also unsure of how to run the test. Any help is appreciated.

**Comment by ricardoV94** [comment]
Thanks, I'll take a look but in the meantime this may give you some hints: https://www.pymc.io/projects/docs/en/stable/contributing/running_the_test_suite.html

**Comment by Diwakar-Gupta** [comment]
Hi @ricardoV94 this is resolved and can be closed.
PR: https://github.com/pymc-devs/pymc/pull/7232

**Comment by ricardoV94** [comment]
It still exists, it should be removed after enough time passed

**Comment by Jiya873** [comment]
Hi @ricardoV94, I checked `pymc/distributions/transforms.py` and found that `SumTo1` is still there and currently lacks a deprecation warning. I want to ask you whether I should add a `FutureWarning` or directly remove the entire class.

**Comment by ricardoV94** [comment]
We can warn first

**Comment by andreruizloera** [comment]
I've opened #8356 implementing the soft deprecation discussed here: a `FutureWarning` on `SumTo1()` instantiation and on `transforms.sum_to_1` access, with `sum_to_1` served lazily via a module `__getattr__` so `import pymc` stays warning-free. The transform remains fully functional, and there's a test covering both access paths. Happy to adjust the approach or messaging.
