### ISSUE TITLE
Converting nonlinear fit from PyMC to PyMC3

### ISSUE THREAD

**Issue by dsuess** [pymc-devs/pymc#709]
I am trying to convert a nonlinear fit routine I have working well in PyMC2 to PyMC3. The statistical model I try to fit is given by

```
y(x) = g(x; mu, sigma) + e(x; noise)
```

where for each x = 1,...,N we have exactly one value `y(x)`, `g` is a Gaussian curve

```
g(x; mu, sigma) = exp(-(x - mu)^2 / (2 * sigma^2))
```

and `e` gives independent N(0,noise)-distributed noise (normally distributed noise).

The PyMC code that implements this model reads (a full implementation with results can be found [here](http://nbviewer.ipython.org/gist/anonymous/89b05fcc44dfb8f097b1)

```
mu = pm.Uniform('mu', lower=0, upper=len(X))
sigma = pm.Uniform('sigma', lower=1, upper=25)

@pm.deterministic
def gaussian(x=X, mu=mu, sigma=sigma):
    return np.exp(-(x - mu)**2 / (2 * sigma**2))

obs = pm.Normal('obs', mu=gaussian, tau=1/NOISE**2, observed=True,
                value=Y)
```

The corresponding PyMC3 implementation I found is

```
with pm3.Model() as model:
    mu = pm3.Uniform('mu', lower=0, upper=len(X))
    sigma = pm3.Uniform('sigma', lower=1, upper=25)
    gaussian = T.exp(-(X - mu)**2 / (2 * sigma**2))
    noise = pm3.Uniform('noise', lower=0, upper=1)
    obs = pm3.Normal('obs', gaussian, sd=NOISE, observed=Y)
```

However, as it shown in the [Notebook](http://nbviewer.ipython.org/gist/anonymous/89b05fcc44dfb8f097b1), the PyMC2 version finds the center `MU=200` with ease, whereas the PyMC3 implementation does not (even with ten times the number of samples). So, what am I missing?

**Comment by twiecki** [comment]
Have you tried a different sampler like `Slice` or `NUTS`? `Metropolis` should clearly work but it might help identify the issue.

**Comment by dsuess** [comment]
Changing the sampler does not help. Also, I have found a minor error (replacing <code>MU=200</code> by <code>MU=200.</code>), but it doesn't fix the issues. Here is a minimal example (even with fixed width of the Gaussian):

```
import pymc3 as pm3
import numpy as np
import matplotlib as mpl

MU = 200.
SIGMA = 10
NOISE = 0.01
SAMPLES = 2000
BURN = 1000

X = np.arange(1000)
Y = np.exp(-(X - MU)**2 / (2 * SIGMA**2)) + NOISE * np.random.randn(len(X))

with pm3.Model() as model:
    mu = pm3.Uniform('mu', lower=0, upper=len(X))
    gaussian = T.exp(-(X - mu)**2 / (2. * SIGMA**2))
    obs = pm3.Normal('obs', gaussian, sd=NOISE, observed=Y)
    step = pm3.Metropolis()
    trace = pm3.sample(BURN + SAMPLES, step, progressbar=True)

print(pm3.summary(trace, vars=['mu']))
pl.plot(X, Y)
pl.vlines([np.mean(trace['mu'])], -0.2, 1.2, color='r')
pl.show()
```

**Comment by twiecki** [comment]
I took a look but also couldn't figure it out yet. I updated your code a bit:

``` python
import pymc3 as pm3
import numpy as np
import matplotlib as mpl
import pylab as pl
import theano.tensor as T

MU = 200.
SIGMA = 20
NOISE = 0.01
SAMPLES = 2000
BURN = 1000

X = np.arange(1000)
Y = np.exp(-(X - MU)**2 / (2 * SIGMA**2)) + NOISE * np.random.randn(len(X))

with pm3.Model() as model:
    mu = pm3.Uniform('mu', lower=0, upper=len(X))
    gaussian = T.exp(-(X - mu)**2 / (2. * SIGMA**2))
    obs = pm3.Normal('obs', gaussian, sd=NOISE, observed=Y)

    step = pm3.Slice()
    trace = pm3.sample(BURN + SAMPLES, step, progressbar=True)

print(pm3.summary(trace, vars=['mu']))
Y_ppc = np.exp(-(X - np.mean(trace['mu']))**2 / (2 * SIGMA**2)) + NOISE * np.random.randn(len(X))
pl.plot(X, Y)
pl.vlines([np.mean(trace['mu'])], -0.2, 1.2, color='r')
pl.plot(X, Y_ppc, 'r')
pl.show()
pm3.traceplot(trace);
```

Somewhere there's an offset coming in and the only place I can imagine is the gaussian. I'm pretty sure it's one of those things that will be super obvious in retrospect.

**Comment by dsuess** [comment]
Strangely, the results get better if one uses a smaller upper for mu (i.e. upper=600 yields good results). Although it doesn't have anything to do with the error (since increasing the sample size by a factor of 100 doesn't change anything), I also don't specify the burn-in period...

**Comment by fonnesbeck** [comment]
Was this resolved?

**Comment by dsuess** [comment]
It looks like this issue has been fixed in the meantime, see [Notebook](https://gist.github.com/dseuss/177f5a5cb544e1a347d413217e71012e)

Thanks!

**Comment by dsuess** [comment]
To be more specific: it only works with the Metropolis sampler. The others (Slice, HamiltonianMC, NUTS) still fail...

**Comment by narendramukherjee** [comment]
I think this issue with NUTS still persists, I see this with a different nonlinear function. I am trying to fit a sinusoidal model, and NUTS has been very bad with all the different model parametrizations I have used. I am posting about this in the discourse forum, could you take a look @twiecki @fonnesbeck @junpenglao 
https://discourse.pymc.io/t/how-to-model-sinusoids-in-white-gaussian-noise/393/12
