### ISSUE TITLE
BUG: pymc import fails with `scipy==1.13.0`

### ISSUE THREAD

**Issue by justinessert** [pymc-devs/pymc#7236]
### Describe the issue:

The import of `pymc` fails with the latest version of `scipy` (`1.13.0`).

> Note: Reverting back to `scipy<1.13` does work for me, but wanted to put this on the radar

### Reproduceable code example:

```python
import pymc as pm
```

### Error message:

<details>

```shell
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/hnf396/opt/anaconda3/envs/aenomoleas/lib/python3.9/site-packages/pymc/__init__.py", line 49, in <module>
    from pymc import _version, gp, ode, sampling
  File "/Users/hnf396/opt/anaconda3/envs/aenomoleas/lib/python3.9/site-packages/pymc/gp/__init__.py", line 15, in <module>
    from pymc.gp import cov, mean, util
  File "/Users/hnf396/opt/anaconda3/envs/aenomoleas/lib/python3.9/site-packages/pymc/gp/util.py", line 30, in <module>
    from pymc.distributions.distribution import Distribution
  File "/Users/hnf396/opt/anaconda3/envs/aenomoleas/lib/python3.9/site-packages/pymc/distributions/__init__.py", line 15, in <module>
    from pymc.distributions.bound import Bound
  File "/Users/hnf396/opt/anaconda3/envs/aenomoleas/lib/python3.9/site-packages/pymc/distributions/bound.py", line 23, in <module>
    from pymc.distributions.continuous import BoundedContinuous, bounded_cont_transform
  File "/Users/hnf396/opt/anaconda3/envs/aenomoleas/lib/python3.9/site-packages/pymc/distributions/continuous.py", line 80, in <module>
    from pymc.distributions.dist_math import (
  File "/Users/hnf396/opt/anaconda3/envs/aenomoleas/lib/python3.9/site-packages/pymc/distributions/dist_math.py", line 39, in <module>
    from pymc.distributions.shape_utils import to_tuple
  File "/Users/hnf396/opt/anaconda3/envs/aenomoleas/lib/python3.9/site-packages/pymc/distributions/shape_utils.py", line 37, in <module>
    from pymc.model import modelcontext
  File "/Users/hnf396/opt/anaconda3/envs/aenomoleas/lib/python3.9/site-packages/pymc/model.py", line 66, in <module>
    from pymc.initial_point import make_initial_point_fn
  File "/Users/hnf396/opt/anaconda3/envs/aenomoleas/lib/python3.9/site-packages/pymc/initial_point.py", line 29, in <module>
    from pymc.util import get_transformed_name, get_untransformed_name, is_transformed_name
  File "/Users/hnf396/opt/anaconda3/envs/aenomoleas/lib/python3.9/site-packages/pymc/util.py", line 20, in <module>
    import arviz
  File "/Users/hnf396/opt/anaconda3/envs/aenomoleas/lib/python3.9/site-packages/arviz/__init__.py", line 34, in <module>
    from .plots import *
  File "/Users/hnf396/opt/anaconda3/envs/aenomoleas/lib/python3.9/site-packages/arviz/plots/__init__.py", line 2, in <module>
    from .autocorrplot import plot_autocorr
  File "/Users/hnf396/opt/anaconda3/envs/aenomoleas/lib/python3.9/site-packages/arviz/plots/autocorrplot.py", line 7, in <module>
    from .plot_utils import default_grid, filter_plotters_list, get_plotting_function
  File "/Users/hnf396/opt/anaconda3/envs/aenomoleas/lib/python3.9/site-packages/arviz/plots/plot_utils.py", line 15, in <module>
    from ..stats.density_utils import kde
  File "/Users/hnf396/opt/anaconda3/envs/aenomoleas/lib/python3.9/site-packages/arviz/stats/__init__.py", line 3, in <module>
    from .density_utils import *
  File "/Users/hnf396/opt/anaconda3/envs/aenomoleas/lib/python3.9/site-packages/arviz/stats/density_utils.py", line 8, in <module>
    from scipy.signal import convolve, convolve2d, gaussian  # pylint: disable=no-name-in-module
ImportError: cannot import name 'gaussian' from 'scipy.signal' (/Users/hnf396/opt/anaconda3/envs/aenomoleas/lib/python3.9/site-packages/scipy/signal/__init__.py)

```

</details>

### PyMC version information:

<details>
PyMC/PyMC3 Version: 5.12.0
PyTensor/Aesara Version: Pytensor - 2.19.0
Python Version: Python 3.9.16
Operating system: Mac OS 14.4.1 
How did you install PyMC/PyMC3: pip
</details>

### Context for the issue:

This issue prevents me from even importing `pymc`. Given that an easy fix is just to install an earlier version of `scipy` though, it's not the absolutely critical. But still something that is fairly important I'd think

**Comment by EliasRas** [comment]
This is due to arviz and should be fixed once the next version is released (by https://github.com/arviz-devs/arviz/pull/2332)

**Comment by ricardoV94** [comment]
Arviz already released a new version, updating should fix it

**Comment by justinessert** [comment]
FYI, The latest release of `arviz==0.18.0` requires Python 3.10, so this effectively means that `pymc`'s latest versions will effectively require Python 3.10 as well (though you would still have the remediation of downgrading `scipy<1.13`)

**Comment by ricardoV94** [comment]
Yes. We also dropped python 3.9 in the next release of PyMC so for older versions one will have to stay in the past
