### ISSUE TITLE
Coal Mining: Disaster model on Getting started gives TypeError: expected type_num 9 (NPY_INT64) got 7

### ISSUE THREAD

**Issue by napsternxg** [pymc-devs/pymc#994]
I am trying to replicate the coal mining disaster model but I keep getting the following error. 

`TypeError: expected type_num 9 (NPY_INT64) got 7`

I even tried specifying the dtypes for all the random variables, to no avail. 

My code can be found at: https://github.com/napsternxg/ipython-notebooks/blob/master/PyMC%20Disaster.ipynb

I am running PyMC3 installed from the git branch
Theano is also installed from the git branch

I am using conda environment on Windows 10 with Python 2.7. 

Any suggestions are welcome.

**Comment by aloctavodia** [comment]
I think this is related to #794

**Comment by walterreade** [comment]
I've been fighting with this for hours (Windows 7, Python 2.7), trying everything I can think of.

Theano: 0.8.0rc1.dev-c6979aeeb39178bf8913dd4c642f60914836be29
Pymc3: from git branch
Numpy: 1.10.4

It _works_ on Linux, but throws the error in Windows. Can't figure out why.

**Comment by twiecki** [comment]
@nouiz is this a known theano windows bug?

**Comment by nouiz** [comment]
Update Theano. Last week we make a PR to fix stuff on Windows:

https://github.com/Theano/Theano/pull/4214

Can you test it to confirm if this fix your problem?

**Comment by walterreade** [comment]
@nouiz I get the same error with all the following:

0.8.0rc1.dev-2fe88f363944cee9f189ab03c735a49795359005
0.8.0rc1.dev-8b7b5b400854d9fbc2a0b6b8f2ad0f9224cc2257
0.8.0rc1.dev-fea9e021b2773e5f3dc9706ed6a1a7b4aed38386

If I've missed something, let me know. Thx.

**Comment by nouiz** [comment]
We merged a bunch of Windows fixes. Can you update Theano to the dev version?

**Comment by walterreade** [comment]
In a new environment, with the latest pymc3 and the following theano installs, I still get the same error.

0.8.0rc1.dev-22b943c3a06ab106fd76650e58de243c217081eb
0.8.0rc1.dev-1567d91d91f91adfc3f6aa140bebe57877adf444

**Comment by napsternxg** [comment]
The example is hanging on the last part of the notebook. I have not yet got the error, but it appears there is some part of the code which makes the kernel hang. My code has been running for more than 20 mins. Can anyone else also replicate this ?
This is the cell input which is causing the hanging. 

```
with disaster_model:
    step1 = pm.NUTS([early_rate, late_rate])

    # Use Metropolis for switchpoint, and missing values since it accommodates discrete variables
    step2 = pm.Metropolis([switchpoint, disasters.missing_values[0]] )

    trace = pm.sample(10000, step=[step1, step2])
```

**Comment by napsternxg** [comment]
**UPDATE:** I confirm that this error is continuing to happen. I installed the latest master branch of theano and pymc3. 

```
TypeError: expected type_num 9 (NPY_INT64) got 7
```

**Comment by nouiz** [comment]
What OS do you have? WHich python? 32 bit python or 64 bit python?

On Thu, Mar 17, 2016 at 9:45 PM, Shubhanshu Mishra <notifications@github.com

**Comment by napsternxg** [comment]
OS: Windows 10
Python: 2.7.11
64 bit
Installed using conda.

**Comment by walterreade** [comment]
I'm on Windows 7, Python 2.7.11, 64 bit, via Anaconda 2.4.1

**Comment by nouiz** [comment]
Try this PR:https://github.com/Theano/Theano/pull/4261

It will give a new error with the information I need to continue.

I don't have this bug on linux with 64 bit python.

**Comment by napsternxg** [comment]
@nouiz I updated my branch to include your error message. 
https://github.com/napsternxg/ipython-notebooks/blob/master/PyMC%20Disaster.ipynb

**Comment by nouiz** [comment]
Thanks. Can you update to the PR again, I added another information. Can
you rerun with this extra Theano flags:

theano.config.exception_verbosity='high'

On Fri, Mar 18, 2016 at 8:16 PM, Shubhanshu Mishra <notifications@github.com

**Comment by napsternxg** [comment]
@nouiz

Updated my notebook with more error messages:

```
TypeError: expected type_num 9 (NPY_INT64) got 7
Apply node that caused the error: AdvancedIncSubtensor1{no_inplace,set}(TensorConstant{[   4    5..   0    1]}, Subtensor{int64:int64:}.0, TensorConstant{[39 83]})
Toposort index: 7
Inputs types: [TensorType(int64, vector), TensorType(int64, vector), TensorType(int64, vector)]
Inputs shapes: [(111L,), (2L,), (2L,)]
Inputs strides: [(8L,), (4L,), (8L,)]
Inputs values: ['not shown', array([0, 2]), array([39, 83], dtype=int64)]
Inputs variables: [TensorConstant{[   4    5..   0    1]}, Subtensor{int64:int64:}.0, TensorConstant{[39 83]}]
Inputs type_num: ['', '', '']
Outputs clients: [[Elemwise{Composite{Switch((i0 * GE(i1, i2)), ((Switch(i3, i4, (i1 * i5)) - scalar_gammaln((i6 + i1))) - i7), i4)}}(Elemwise{ge,no_inplace}.0, AdvancedIncSubtensor1{no_inplace,set}.0, TensorConstant{(1L,) of 0}, InplaceDimShuffle{x}.0, TensorConstant{(1L,) of -inf}, Elemwise{log,no_inplace}.0, TensorConstant{(1L,) of 1}, Elemwise{Composite{Switch(GE(i0, i1), i2, i3)}}.0)]]

Backtrace when the node is created(use Theano flag traceback.limit=N to make it longer):
  File "E:\Anaconda\lib\site-packages\IPython\core\interactiveshell.py", line 2723, in run_cell
    interactivity=interactivity, compiler=compiler, result=result)
  File "E:\Anaconda\lib\site-packages\IPython\core\interactiveshell.py", line 2825, in run_ast_nodes
    if self.run_code(code, result):
  File "E:\Anaconda\lib\site-packages\IPython\core\interactiveshell.py", line 2885, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-5-360c93d12d72>", line 13, in <module>
    disasters = pm.Poisson('disasters', rate, observed=disaster_data)
  File "E:\Anaconda\lib\site-packages\pymc3\distributions\distribution.py", line 25, in __new__
    return model.Var(name, dist, data)
  File "E:\Anaconda\lib\site-packages\pymc3\model.py", line 272, in Var
    var = ObservedRV(name=name, data=data, distribution=dist, model=self)
  File "E:\Anaconda\lib\site-packages\pymc3\model.py", line 544, in __init__
    data = as_tensor(data, name,model,distribution.dtype)
  File "E:\Anaconda\lib\site-packages\pymc3\model.py", line 512, in as_tensor
    missing_values)

Debugprint of the apply node: 
AdvancedIncSubtensor1{no_inplace,set} [id A] <TensorType(int64, vector)> ''   
 |TensorConstant{[   4    5..   0    1]} [id B] <TensorType(int64, vector)>
 |Subtensor{int64:int64:} [id C] <TensorType(int64, vector)> ''   
 | |inarray1 [id D] <TensorType(int64, vector)>
 | |Constant{0} [id E] <int64>
 | |Constant{2} [id F] <int64>
 |TensorConstant{[39 83]} [id G] <TensorType(int64, vector)>

Storage map footprint:
 - Elemwise{Composite{Switch(GE(i0, i1), i2, i3)}}.0, Shape: (111L,), ElemSize: 8 Byte(s), TotalSize: 888 Byte(s)
 - TensorConstant{[   4    5..   0    1]}, Shape: (111L,), ElemSize: 8 Byte(s), TotalSize: 888 Byte(s)
 - TensorConstant{[1851 1852..1960 1961]}, Shape: (111L,), ElemSize: 4 Byte(s), TotalSize: 444 Byte(s)
 - Elemwise{ge,no_inplace}.0, Shape: (111L,), ElemSize: 1 Byte(s), TotalSize: 111 Byte(s)
 - TensorConstant{[39 83]}, Shape: (2L,), ElemSize: 8 Byte(s), TotalSize: 16 Byte(s)
 - late_rate_log_shared, Shared Input, Shape: (), ElemSize: 8 Byte(s), TotalSize: 8.0 Byte(s)
 - early_rate_log_shared, Shared Input, Shape: (), ElemSize: 8 Byte(s), TotalSize: 8.0 Byte(s)
 - inarray1, Input, Shape: (2L,), ElemSize: 4 Byte(s), TotalSize: 8 Byte(s)
 - switchpoint_shared, Shared Input, Shape: (), ElemSize: 8 Byte(s), TotalSize: 8.0 Byte(s)
 - Constant{0}, Shape: (), ElemSize: 8 Byte(s), TotalSize: 8.0 Byte(s)
 - TensorConstant{(1L,) of 1}, Shape: (1L,), ElemSize: 8 Byte(s), TotalSize: 8 Byte(s)
 - Constant{2}, Shape: (), ElemSize: 8 Byte(s), TotalSize: 8.0 Byte(s)
 - Subtensor{int64:int64:}.0, Shape: (2L,), ElemSize: 4 Byte(s), TotalSize: 8 Byte(s)
 - inarray, Input, Shape: (2L,), ElemSize: 4 Byte(s), TotalSize: 8 Byte(s)
 - TensorConstant{(1L,) of -inf}, Shape: (1L,), ElemSize: 4 Byte(s), TotalSize: 4 Byte(s)
 - TensorConstant{(1L,) of 0}, Shape: (1L,), ElemSize: 1 Byte(s), TotalSize: 1 Byte(s)
 TotalSize: 2416.0 Byte(s) 0.000 GB
 TotalSize inputs: 1417.0 Byte(s) 0.000 GB

```

**Comment by nouiz** [comment]
I had a bug in the way I got the information. Can you update the PR and use
this extra Theano flag:

exception_verbosity='high'

On Sat, Mar 19, 2016 at 1:19 AM, Shubhanshu Mishra <notifications@github.com

**Comment by lamblin** [comment]
@napsternxg Were you able to test the latest version of the PR? I would like to know if it works correctly before I merge it.

**Comment by nouiz** [comment]
Just to be sure, that PR only give more information to the error, so report
the new error. It should help us find the root and fix it.

**Comment by napsternxg** [comment]
Hi @nouiz this is the new error, I don't see a difference in the error. I am using the latest PR and also the `exception_verbosity='high'` flag. 

I have updated my notebook on github. 

```
TypeError: expected type_num 9 (NPY_INT64) got 7
Apply node that caused the error: AdvancedIncSubtensor1{no_inplace,set}(TensorConstant{[   4    5..   0    1]}, Subtensor{int64:int64:}.0, TensorConstant{[39 83]})
Toposort index: 7
Inputs types: [TensorType(int64, vector), TensorType(int64, vector), TensorType(int64, vector)]
Inputs shapes: [(111L,), (2L,), (2L,)]
Inputs strides: [(8L,), (4L,), (8L,)]
Inputs values: ['not shown', array([-1,  0]), array([39, 83], dtype=int64)]
Inputs variables: [TensorConstant{[   4    5..   0    1]}, Subtensor{int64:int64:}.0, TensorConstant{[39 83]}]
Inputs type_num: ['', '', '']
Outputs clients: [[Elemwise{Composite{Switch((i0 * GE(i1, i2)), ((Switch(i3, i4, (i1 * i5)) - scalar_gammaln((i6 + i1))) - i7), i4)}}(Elemwise{ge,no_inplace}.0, AdvancedIncSubtensor1{no_inplace,set}.0, TensorConstant{(1L,) of 0}, InplaceDimShuffle{x}.0, TensorConstant{(1L,) of -inf}, Elemwise{log,no_inplace}.0, TensorConstant{(1L,) of 1}, Elemwise{Composite{Switch(GE(i0, i1), i2, i3)}}.0)]]

Backtrace when the node is created(use Theano flag traceback.limit=N to make it longer):
  File "E:\Anaconda\lib\site-packages\IPython\core\interactiveshell.py", line 2723, in run_cell
    interactivity=interactivity, compiler=compiler, result=result)
  File "E:\Anaconda\lib\site-packages\IPython\core\interactiveshell.py", line 2825, in run_ast_nodes
    if self.run_code(code, result):
  File "E:\Anaconda\lib\site-packages\IPython\core\interactiveshell.py", line 2885, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-4-360c93d12d72>", line 13, in <module>
    disasters = pm.Poisson('disasters', rate, observed=disaster_data)
  File "E:\Anaconda\lib\site-packages\pymc3\distributions\distribution.py", line 25, in __new__
    return model.Var(name, dist, data)
  File "E:\Anaconda\lib\site-packages\pymc3\model.py", line 272, in Var
    var = ObservedRV(name=name, data=data, distribution=dist, model=self)
  File "E:\Anaconda\lib\site-packages\pymc3\model.py", line 544, in __init__
    data = as_tensor(data, name,model,distribution.dtype)
  File "E:\Anaconda\lib\site-packages\pymc3\model.py", line 512, in as_tensor
    missing_values)

Debugprint of the apply node: 
AdvancedIncSubtensor1{no_inplace,set} [id A] <TensorType(int64, vector)> ''   
 |TensorConstant{[   4    5..   0    1]} [id B] <TensorType(int64, vector)>
 |Subtensor{int64:int64:} [id C] <TensorType(int64, vector)> ''   
 | |inarray1 [id D] <TensorType(int64, vector)>
 | |Constant{0} [id E] <int64>
 | |Constant{2} [id F] <int64>
 |TensorConstant{[39 83]} [id G] <TensorType(int64, vector)>

Storage map footprint:
 - Elemwise{Composite{Switch(GE(i0, i1), i2, i3)}}.0, Shape: (111L,), ElemSize: 8 Byte(s), TotalSize: 888 Byte(s)
 - TensorConstant{[   4    5..   0    1]}, Shape: (111L,), ElemSize: 8 Byte(s), TotalSize: 888 Byte(s)
 - TensorConstant{[1851 1852..1960 1961]}, Shape: (111L,), ElemSize: 4 Byte(s), TotalSize: 444 Byte(s)
 - Elemwise{ge,no_inplace}.0, Shape: (111L,), ElemSize: 1 Byte(s), TotalSize: 111 Byte(s)
 - TensorConstant{[39 83]}, Shape: (2L,), ElemSize: 8 Byte(s), TotalSize: 16 Byte(s)
 - Constant{2}, Shape: (), ElemSize: 8 Byte(s), TotalSize: 8.0 Byte(s)
 - Constant{0}, Shape: (), ElemSize: 8 Byte(s), TotalSize: 8.0 Byte(s)
 - inarray1, Input, Shape: (2L,), ElemSize: 4 Byte(s), TotalSize: 8 Byte(s)
 - inarray, Input, Shape: (2L,), ElemSize: 4 Byte(s), TotalSize: 8 Byte(s)
 - switchpoint_shared, Shared Input, Shape: (), ElemSize: 8 Byte(s), TotalSize: 8.0 Byte(s)
 - early_rate_log_shared, Shared Input, Shape: (), ElemSize: 8 Byte(s), TotalSize: 8.0 Byte(s)
 - late_rate_log_shared, Shared Input, Shape: (), ElemSize: 8 Byte(s), TotalSize: 8.0 Byte(s)
 - TensorConstant{(1L,) of 1}, Shape: (1L,), ElemSize: 8 Byte(s), TotalSize: 8 Byte(s)
 - Subtensor{int64:int64:}.0, Shape: (2L,), ElemSize: 4 Byte(s), TotalSize: 8 Byte(s)
 - TensorConstant{(1L,) of -inf}, Shape: (1L,), ElemSize: 4 Byte(s), TotalSize: 4 Byte(s)
 - TensorConstant{(1L,) of 0}, Shape: (1L,), ElemSize: 1 Byte(s), TotalSize: 1 Byte(s)
 TotalSize: 2416.0 Byte(s) 0.000 GB
 TotalSize inputs: 1417.0 Byte(s) 0.000 GB
```

**Comment by nouiz** [comment]
That is strange. I double checked and it work here. Can you verify that you
tested with commit: f35ed2e
https://github.com/Theano/Theano/pull/4261/commits/f35ed2e424cf3c4161404494aa2b040187047b1e

**Comment by lamblin** [comment]
FWIW, I think the original issue comes from [AdvIncSubtensor1.copy_of_x](https://github.com/Theano/Theano/blob/master/theano/tensor/subtensor.py#L1914-L1939), since we pass `NULL` as `dtype`, numpy feels free to use another equivalent dtype that has a different `typenum`.
This is the same issue fixed by [`_asarray`](https://github.com/Theano/Theano/blob/master/theano/misc/safe_asarray.py`) when Theano calls NumPy code.

In that case, I think we should extract the dtype (or typenum?) from the original array and use it explicitly.

**Comment by napsternxg** [comment]
@nouiz Here is what I have done:

```
pip install git+https://github.com/nouiz/Theano.git@f35ed2e424cf3c4161404494aa2b040187047b1e
```

Then I re-ran my notebook. The new results can be seen at the link: 

https://github.com/napsternxg/ipython-notebooks/blob/master/PyMC%20Disaster.ipynb

**Comment by nouiz** [comment]
I just pushed to that PR a commit that implement @lamblin suggested fix.
Can you try it?

On Fri, Apr 8, 2016 at 11:29 PM, Shubhanshu Mishra <notifications@github.com

**Comment by Paul-Yuchao-Dong** [comment]
Ran into the same problem when try to follow along [https://github.com/markdregan/Bayesian-Modelling-in-Python/blob/master/Section%202.%20Model%20checking.ipynb](url)

I have upgraded to the latest commit of Theano, as git suggested "Could not find a tag or branch 'f35ed2e424cf3c4161404494aa2b040187047b1e', assuming commit."

Running on 32-bit Anaconda ==4.0 Python == 2.7 on windows7 provided below trace:

---

TypeError                                 Traceback (most recent call last)
<ipython-input-5-3a4f2e83047f> in <module>()
      5     step2 = pm.Metropolis([switchpoint, disasters.missing_values[0]] )
      6 
----> 7     trace = pm.sample(10000, step=[step1, step2])

C:\Users\paul.dong\Documents\Anaconda\lib\site-packages\pymc3\sampling.pyc in sample(draws, step, start, trace, chain, njobs, tune, progressbar, model, random_seed)
    147         sample_func = _sample
    148 
--> 149     return sample_func(**sample_args)
    150 
    151 

C:\Users\paul.dong\Documents\Anaconda\lib\site-packages\pymc3\sampling.pyc in _sample(draws, step, start, trace, chain, tune, progressbar, model, random_seed)
    156     progress = progress_bar(draws)
    157     try:
--> 158         for i, strace in enumerate(sampling):
    159             if progressbar:
    160                 progress.update(i)

C:\Users\paul.dong\Documents\Anaconda\lib\site-packages\pymc3\sampling.pyc in _iter_sample(draws, step, start, trace, chain, tune, model, random_seed)
    238         if i == tune:
    239             step = stop_tuning(step)
--> 240         point = step.step(point)
    241         strace.record(point)
    242         yield strace

C:\Users\paul.dong\Documents\Anaconda\lib\site-packages\pymc3\step_methods\compound.pyc in step(self, point)
     12     def step(self, point):
     13         for method in self.methods:
---> 14             point = method.step(point)
     15         return point

C:\Users\paul.dong\Documents\Anaconda\lib\site-packages\pymc3\step_methods\compound.pyc in step(self, point)
     12     def step(self, point):
     13         for method in self.methods:
---> 14             point = method.step(point)
     15         return point

C:\Users\paul.dong\Documents\Anaconda\lib\site-packages\pymc3\step_methods\arraystep.pyc in step(self, point)
    116         bij = DictToArrayBijection(self.ordering, point)
    117 
--> 118         apoint = self.astep(bij.map(point))
    119         return bij.rmap(apoint)
    120 

C:\Users\paul.dong\Documents\Anaconda\lib\site-packages\pymc3\step_methods\metropolis.pyc in astep(self, q0)
    123             q = q0 + delta
    124 
--> 125         q_new = metrop_select(self.delta_logp(q, q0), q, q0)
    126 
    127         if q_new is q:

C:\Users\paul.dong\Documents\Anaconda\lib\site-packages\theano\compile\function_module.pyc in **call**(self, _args, *_kwargs)
    869                     node=self.fn.nodes[self.fn.position_of_error],
    870                     thunk=thunk,
--> 871                     storage_map=getattr(self.fn, 'storage_map', None))
    872             else:
    873                 # old-style linkers raise their own exceptions

C:\Users\paul.dong\Documents\Anaconda\lib\site-packages\theano\gof\link.pyc in raise_with_op(node, thunk, exc_info, storage_map)
    316         # extra long error message in that case.
    317         pass
--> 318     reraise(exc_type, exc_value, exc_trace)
    319 
    320 

C:\Users\paul.dong\Documents\Anaconda\lib\site-packages\theano\compile\function_module.pyc in **call**(self, _args, *_kwargs)
    857         t0_fn = time.time()
    858         try:
--> 859             outputs = self.fn()
    860         except Exception:
    861             if hasattr(self.fn, 'position_of_error'):

TypeError: expected type_num 9 (NPY_INT64) got 7
Apply node that caused the error: AdvancedIncSubtensor1{no_inplace,set}(TensorConstant{[   4    5..   0    1]}, Subtensor{int64:int64:}.0, TensorConstant{[39 83]})
Toposort index: 7
Inputs types: [TensorType(int64, vector), TensorType(int64, vector), TensorType(int32, vector)]
Inputs shapes: [(111,), (2,), (2,)]
Inputs strides: [(8,), (4,), (4,)]
Inputs values: ['not shown', array([ 2, -1]), array([39, 83])]
Inputs variables: [TensorConstant{[   4    5..   0    1]}, Subtensor{int64:int64:}.0, TensorConstant{[39 83]}]
Inputs type_num: [9, 7, 7]
Outputs clients: [[Elemwise{Composite{Switch((i0 \* GE(i1, i2)), ((Switch(i3, i4, (i1 \* i5)) - scalar_gammaln((i6 + i1))) - i7), i4)}}(Elemwise{ge,no_inplace}.0, AdvancedIncSubtensor1{no_inplace,set}.0, TensorConstant{(1,) of 0}, InplaceDimShuffle{x}.0, TensorConstant{(1,) of -inf}, Elemwise{log,no_inplace}.0, TensorConstant{(1,) of 1}, Elemwise{Composite{Switch(GE(i0, i1), i2, i3)}}.0)]]

Backtrace when the node is created(use Theano flag traceback.limit=N to make it longer):
  File "C:\Users\paul.dong\Documents\Anaconda\lib\site-packages\IPython\core\interactiveshell.py", line 2723, in run_cell
    interactivity=interactivity, compiler=compiler, result=result)
  File "C:\Users\paul.dong\Documents\Anaconda\lib\site-packages\IPython\core\interactiveshell.py", line 2825, in run_ast_nodes
    if self.run_code(code, result):
  File "C:\Users\paul.dong\Documents\Anaconda\lib\site-packages\IPython\core\interactiveshell.py", line 2885, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-4-360c93d12d72>", line 13, in <module>
    disasters = pm.Poisson('disasters', rate, observed=disaster_data)
  File "C:\Users\paul.dong\Documents\Anaconda\lib\site-packages\pymc3\distributions\distribution.py", line 25, in **new**
    return model.Var(name, dist, data)
  File "C:\Users\paul.dong\Documents\Anaconda\lib\site-packages\pymc3\model.py", line 272, in Var
    var = ObservedRV(name=name, data=data, distribution=dist, model=self)
  File "C:\Users\paul.dong\Documents\Anaconda\lib\site-packages\pymc3\model.py", line 544, in **init**
    data = as_tensor(data, name,model,distribution.dtype)
  File "C:\Users\paul.dong\Documents\Anaconda\lib\site-packages\pymc3\model.py", line 512, in as_tensor
    missing_values)

Debugprint of the apply node: 
AdvancedIncSubtensor1{no_inplace,set} [id A] <TensorType(int64, vector)> ''  
 |TensorConstant{[   4    5..   0    1]} [id B] <TensorType(int64, vector)>
 |Subtensor{int64:int64:} [id C] <TensorType(int64, vector)> ''  
 | |inarray1 [id D] <TensorType(int64, vector)>
 | |Constant{0} [id E] <int64>
 | |Constant{2} [id F] <int64>
 |TensorConstant{[39 83]} [id G] <TensorType(int32, vector)>

Storage map footprint:
- TensorConstant{[   4    5..   0    1]}, Shape: (111,), ElemSize: 8 Byte(s), TotalSize: 888 Byte(s)
- Elemwise{Composite{Switch(GE(i0, i1), i2, i3)}}.0, Shape: (111,), ElemSize: 8 Byte(s), TotalSize: 888 Byte(s)
- TensorConstant{[1851 1852..1960 1961]}, Shape: (111,), ElemSize: 4 Byte(s), TotalSize: 444 Byte(s)
- Elemwise{ge,no_inplace}.0, Shape: (111,), ElemSize: 1 Byte(s), TotalSize: 111 Byte(s)
- late_rate_log_shared, Shared Input, Shape: (), ElemSize: 8 Byte(s), TotalSize: 8.0 Byte(s)
- Subtensor{int64:int64:}.0, Shape: (2,), ElemSize: 4 Byte(s), TotalSize: 8 Byte(s)
- Constant{0}, Shape: (), ElemSize: 8 Byte(s), TotalSize: 8.0 Byte(s)
- Constant{2}, Shape: (), ElemSize: 8 Byte(s), TotalSize: 8.0 Byte(s)
- TensorConstant{[39 83]}, Shape: (2,), ElemSize: 4 Byte(s), TotalSize: 8 Byte(s)
- inarray1, Input, Shape: (2,), ElemSize: 4 Byte(s), TotalSize: 8 Byte(s)
- switchpoint_shared, Shared Input, Shape: (), ElemSize: 8 Byte(s), TotalSize: 8.0 Byte(s)
- early_rate_log_shared, Shared Input, Shape: (), ElemSize: 8 Byte(s), TotalSize: 8.0 Byte(s)
- inarray, Input, Shape: (2,), ElemSize: 4 Byte(s), TotalSize: 8 Byte(s)
- TensorConstant{(1,) of 1}, Shape: (1,), ElemSize: 8 Byte(s), TotalSize: 8 Byte(s)
- TensorConstant{(1,) of -inf}, Shape: (1,), ElemSize: 4 Byte(s), TotalSize: 4 Byte(s)
- TensorConstant{(1,) of 0}, Shape: (1,), ElemSize: 1 Byte(s), TotalSize: 1 Byte(s)
  TotalSize: 2408.0 Byte(s) 0.000 GB
  TotalSize inputs: 1409.0 Byte(s) 0.000 GB

Hope this helps and looking forward to see this issue fixed.

**Comment by napsternxg** [comment]
@nouiz, @lamblin I am doing the following steps:

```
pip install --upgrade --no-deps git+https://github.com/nouiz/Theano.git@err_msg_inputs
```

This is the part of the error which is updated:

```
TypeError: expected type_num 9 (NPY_INT64) got 7
Apply node that caused the error: AdvancedIncSubtensor1{no_inplace,set}(TensorConstant{[   4    5..   0    1]}, Subtensor{int64:int64:}.0, TensorConstant{[39 83]})
Toposort index: 7
Inputs types: [TensorType(int64, vector), TensorType(int64, vector), TensorType(int64, vector)]
Inputs shapes: [(111L,), (2L,), (2L,)]
Inputs strides: [(8L,), (4L,), (8L,)]
Inputs values: ['not shown', array([2, 1]), array([39, 83], dtype=int64)]
Inputs type_num: [9, 7, 9]
Outputs clients: [[Elemwise{Composite{Switch((i0 * GE(i1, i2)), ((Switch(i3, i4, (i1 * i5)) - scalar_gammaln((i6 + i1))) - i7), i4)}}(Elemwise{ge,no_inplace}.0, AdvancedIncSubtensor1{no_inplace,set}.0, TensorConstant{(1L,) of 0}, InplaceDimShuffle{x}.0, TensorConstant{(1L,) of -inf}, Elemwise{log,no_inplace}.0, TensorConstant{(1L,) of 1}, Elemwise{Composite{Switch(GE(i0, i1), i2, i3)}}.0)]]

Backtrace when the node is created(use Theano flag traceback.limit=N to make it longer):
  File "E:\Anaconda\lib\site-packages\IPython\core\interactiveshell.py", line 2723, in run_cell
    interactivity=interactivity, compiler=compiler, result=result)
  File "E:\Anaconda\lib\site-packages\IPython\core\interactiveshell.py", line 2825, in run_ast_nodes
    if self.run_code(code, result):
  File "E:\Anaconda\lib\site-packages\IPython\core\interactiveshell.py", line 2885, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-4-360c93d12d72>", line 13, in <module>
    disasters = pm.Poisson('disasters', rate, observed=disaster_data)
  File "E:\Anaconda\lib\site-packages\pymc3\distributions\distribution.py", line 25, in __new__
    return model.Var(name, dist, data)
  File "E:\Anaconda\lib\site-packages\pymc3\model.py", line 272, in Var
    var = ObservedRV(name=name, data=data, distribution=dist, model=self)
  File "E:\Anaconda\lib\site-packages\pymc3\model.py", line 544, in __init__
    data = as_tensor(data, name,model,distribution.dtype)
  File "E:\Anaconda\lib\site-packages\pymc3\model.py", line 512, in as_tensor
    missing_values)

Debugprint of the apply node: 
AdvancedIncSubtensor1{no_inplace,set} [id A] <TensorType(int64, vector)> ''   
 |TensorConstant{[   4    5..   0    1]} [id B] <TensorType(int64, vector)>
 |Subtensor{int64:int64:} [id C] <TensorType(int64, vector)> ''   
 | |inarray1 [id D] <TensorType(int64, vector)>
 | |Constant{0} [id E] <int64>
 | |Constant{2} [id F] <int64>
 |TensorConstant{[39 83]} [id G] <TensorType(int64, vector)>

Storage map footprint:
 - TensorConstant{[   4    5..   0    1]}, Shape: (111L,), ElemSize: 8 Byte(s), TotalSize: 888 Byte(s)
 - Elemwise{Composite{Switch(GE(i0, i1), i2, i3)}}.0, Shape: (111L,), ElemSize: 8 Byte(s), TotalSize: 888 Byte(s)
 - TensorConstant{[1851 1852..1960 1961]}, Shape: (111L,), ElemSize: 4 Byte(s), TotalSize: 444 Byte(s)
 - Elemwise{ge,no_inplace}.0, Shape: (111L,), ElemSize: 1 Byte(s), TotalSize: 111 Byte(s)
 - TensorConstant{[39 83]}, Shape: (2L,), ElemSize: 8 Byte(s), TotalSize: 16 Byte(s)
 - Constant{2}, Shape: (), ElemSize: 8 Byte(s), TotalSize: 8.0 Byte(s)
 - early_rate_log_shared, Shared Input, Shape: (), ElemSize: 8 Byte(s), TotalSize: 8.0 Byte(s)
 - inarray1, Input, Shape: (2L,), ElemSize: 4 Byte(s), TotalSize: 8 Byte(s)
 - Subtensor{int64:int64:}.0, Shape: (2L,), ElemSize: 4 Byte(s), TotalSize: 8 Byte(s)
 - TensorConstant{(1L,) of 1}, Shape: (1L,), ElemSize: 8 Byte(s), TotalSize: 8 Byte(s)
 - switchpoint_shared, Shared Input, Shape: (), ElemSize: 8 Byte(s), TotalSize: 8.0 Byte(s)
 - inarray, Input, Shape: (2L,), ElemSize: 4 Byte(s), TotalSize: 8 Byte(s)
 - Constant{0}, Shape: (), ElemSize: 8 Byte(s), TotalSize: 8.0 Byte(s)
 - late_rate_log_shared, Shared Input, Shape: (), ElemSize: 8 Byte(s), TotalSize: 8.0 Byte(s)
 - TensorConstant{(1L,) of -inf}, Shape: (1L,), ElemSize: 4 Byte(s), TotalSize: 4 Byte(s)
 - TensorConstant{(1L,) of 0}, Shape: (1L,), ElemSize: 1 Byte(s), TotalSize: 1 Byte(s)
 TotalSize: 2416.0 Byte(s) 0.000 GB
 TotalSize inputs: 1417.0 Byte(s) 0.000 GB
```

I have updated the error messages in the notebook:
https://github.com/napsternxg/ipython-notebooks/blob/master/PyMC%20Disaster.ipynb

**Comment by nouiz** [comment]
It seam that a previous node generated bad output dtype. Can you try with
this flag to detect the earlier problem? mode=DebugMode

What are your Theano flags? Could it be that the input of a Theano function
isn't the right one and you disable some Theano check?

On Mon, Apr 18, 2016 at 1:53 PM, Shubhanshu Mishra <notifications@github.com

**Comment by napsternxg** [comment]
@nouiz I tried with DebugMode and now I get the following error:

```
InvalidValueError: InvalidValueError
        type(variable) = TensorType(float32, scalar)
        variable       = TensorConstant{-inf}
        type(value)    = <type 'numpy.ndarray'>
        dtype(value)   = float32
        shape(value)   = ()
        value          = -inf
        min(value)     = -inf
        max(value)     = -inf
        isfinite       = False
        client_node    = None
        hint           = Graph Input 'TensorConstant{-inf}' has invalid value -inf
        specific_hint  = none
        context        = ...
  TensorConstant{-inf} [id A]
```

I checked my input data, but I don't know where the -inf value is coming from. Please have a look at the full notebook at: https://github.com/napsternxg/ipython-notebooks/blob/master/PyMC%20Disaster.ipynb

**Comment by lamblin** [comment]
You can disable checking for inf/invalid values in DebugMode by setting `DebugMode.check_finite = False` in the configuration. You would have to do that before importing Theano, though, or directly set `theano.compile.DebugMode.check_isfinite = False` instead.

**Comment by fonnesbeck** [comment]
Has anyone made any headway in debugging this issue? Seems to be a show-stopper for Windows users.

**Comment by Paul-Yuchao-Dong** [comment]
@fonnesbeck Many thanks for considering the rest of us windows users! Under a corporate machine, pretty hard to get the docker setup.

**Comment by unkufunku** [comment]
I'd like to add that I've just installed latest releases theano 0.8.2 and pymc3 3.0rc2 and experiencing type error as this issue#. windows 10, x64 with anaconda3, python 3.5.2.
Trying examples given in Bayesian-Modelling-in-Python (master) Section 2. Model checking.ipynb

Apologies for not knowing what next to do.
Any assistance appreciated.
frank

Error as follows:-
Applied interval-transform to mu and added transformed mu_interval_ to model.
  0%|                                               | 0/200000 [00:00<?, ?it/s]

---

TypeError                                 Traceback (most recent call last)
C:\Anaconda3\lib\site-packages\theano\compile\function_module.py in **call**(self, _args, *_kwargs)
    858         try:
--> 859             outputs = self.fn()
    860         except Exception:

TypeError: expected type_num 9 (NPY_INT64) got 7

During handling of the above exception, another exception occurred:

TypeError                                 Traceback (most recent call last)
<ipython-input-2-8528decefd8e> in <module>()
      7     start = pm.find_MAP()
      8     step = pm.Metropolis()
----> 9     trace = pm.sample(200000, step, start=start, progressbar=True)

C:\Anaconda3\lib\site-packages\pymc3\sampling.py in sample(draws, step, start, trace, chain, njobs, tune, progressbar, model, random_seed)
    155         sample_func = _sample
    156 
--> 157     return sample_func(**sample_args)
    158 
    159 

C:\Anaconda3\lib\site-packages\pymc3\sampling.py in _sample(draws, step, start, trace, chain, tune, progressbar, model, random_seed)
    165         sampling = tqdm(sampling, total=draws)
    166     try:
--> 167         for strace in sampling:
    168             pass
    169     except KeyboardInterrupt:

C:\Anaconda3\lib\site-packages\tqdm_tqdm.py in **iter**(self)
    711 """, fp_write=getattr(self.fp, 'write', sys.stderr.write))
    712 
--> 713             for obj in iterable:
    714                 yield obj
    715                 # Update and print the progressbar.

C:\Anaconda3\lib\site-packages\pymc3\sampling.py in _iter_sample(draws, step, start, trace, chain, tune, model, random_seed)
    247         if i == tune:
    248             step = stop_tuning(step)
--> 249         point = step.step(point)
    250         strace.record(point)
    251         yield strace

C:\Anaconda3\lib\site-packages\pymc3\step_methods\compound.py in step(self, point)
     14     def step(self, point):
     15         for method in self.methods:
---> 16             point = method.step(point)
     17         return point

C:\Anaconda3\lib\site-packages\pymc3\step_methods\arraystep.py in step(self, point)
    140         bij = DictToArrayBijection(self.ordering, point)
    141 
--> 142         apoint = self.astep(bij.map(point))
    143         return bij.rmap(apoint)
    144 

C:\Anaconda3\lib\site-packages\pymc3\step_methods\metropolis.py in astep(self, q0)
    135             q = q0 + delta
    136 
--> 137         q_new = metrop_select(self.delta_logp(q, q0), q, q0)
    138 
    139         if q_new is q:

C:\Anaconda3\lib\site-packages\theano\compile\function_module.py in **call**(self, _args, *_kwargs)
    869                     node=self.fn.nodes[self.fn.position_of_error],
    870                     thunk=thunk,
--> 871                     storage_map=getattr(self.fn, 'storage_map', None))
    872             else:
    873                 # old-style linkers raise their own exceptions

C:\Anaconda3\lib\site-packages\theano\gof\link.py in raise_with_op(node, thunk, exc_info, storage_map)
    312         # extra long error message in that case.
    313         pass
--> 314     reraise(exc_type, exc_value, exc_trace)
    315 
    316 

C:\Anaconda3\lib\site-packages\six.py in reraise(tp, value, tb)
    683             value = tp()
    684         if value.**traceback** is not tb:
--> 685             raise value.with_traceback(tb)
    686         raise value
    687 

C:\Anaconda3\lib\site-packages\theano\compile\function_module.py in **call**(self, _args, *_kwargs)
    857         t0_fn = time.time()
    858         try:
--> 859             outputs = self.fn()
    860         except Exception:
    861             if hasattr(self.fn, 'position_of_error'):

TypeError: expected type_num 9 (NPY_INT64) got 7
Apply node that caused the error: Elemwise{Composite{(Switch((EQ(i0, i1) \* EQ(i2, i1)), i1, Switch((GE(i0, i1) \* GE(i2, i1)), ((Switch(EQ(i0, i1), i3, (i2 \* log(i0))) - scalar_gammaln((i4 + i2))) - i0), i3)) - Switch((EQ(i0, i1) \* EQ(i5, i1)), i1, Switch((GE(i0, i1) \* GE(i5, i1)), ((Switch(EQ(i0, i1), i3, (i5 \* log(i0))) - scalar_gammaln((i4 + i5))) - i0), i3)))}}[(0, 0)](mu, TensorConstant{0}, Subtensor{int64}.0, TensorConstant{-inf}, TensorConstant{1}, Subtensor{int64}.0)
Toposort index: 4
Inputs types: [TensorType(float64, scalar), TensorType(int8, scalar), TensorType(int64, scalar), TensorType(float32, scalar), TensorType(int64, scalar), TensorType(int64, scalar)]
Inputs shapes: [(), (), (), (), (), ()]
Inputs strides: [(), (), (), (), (), ()]
Inputs values: [array(18.16396271322722), array(0, dtype=int8), array(49), array(-inf, dtype=float32), array(1, dtype=int64), array(50)]
Outputs clients: [['output']]

HINT: Re-running with most Theano optimization disabled could give you a back-trace of when this node was created. This can be done with by setting the Theano flag 'optimizer=fast_compile'. If that does not work, Theano optimizations can be disabled with 'optimizer=None'.
HINT: Use the Theano flag 'exception_verbosity=high' for a debugprint and storage map footprint of this apply node.

**Comment by twiecki** [comment]
@unkufunku Can you try installing theano master?

**Comment by unkufunku** [comment]
@twiecki Tried simple approach that shows I have latest released version of theano.
If you are referring to clone git, then can try that after removing conda / conda-forge version.
below is my attempt:-
(C:\Anaconda3) C:\Users\Franc>activate root

(root) C:\Users\Franc>conda update --no-deps theano
Using Anaconda API: https://api.anaconda.org
Fetching package metadata .........

# All requested packages already installed.

# packages in environment at C:\Anaconda3:

#
theano                    0.8.2                    py35_0

(root) C:\Users\Franc>pip install --upgrade --no-deps theano
Requirement already up-to-date: theano in c:\anaconda3\lib\site-packages

(root) C:\Users\Franc>pip install --upgrade theano
Requirement already up-to-date: theano in c:\anaconda3\lib\site-packages
Requirement already up-to-date: numpy>=1.7.1 in c:\anaconda3\lib\site-packages (from theano)
Requirement already up-to-date: scipy>=0.11 in c:\anaconda3\lib\site-packages (from theano)
Requirement already up-to-date: six>=1.9.0 in c:\anaconda3\lib\site-packages (from theano)
frank

**Comment by lamblin** [comment]
He was indeed referring to the development version from git.

**Comment by unkufunku** [comment]
@lamblin thanks for clarification. 
I've taken several approaches without success.
Had m2w64 toolchain installed and linked to theano 0.8.2 until removed as above.

1) GIT clone method - setup.py develop to install under site-packages
git clone git://github.com/Theano/Theano.git
cd Theano
python setup.py develop

started spyder
Now getting,
IP[1]:  import theano
if sys.platform == 'win32' and sys.version_info[0:2] == (3, 5):
    raise RuntimeError(
        "Theano do not support Python 3.5 on Windows. Use Python 2.7 or 3.4.")

I previously had this when compiler hadn't been installed and links weren't made using conda.
Note:
---> .pth file not created
---->unable to run theano-nose .... not found

To get a 'clean' root environment, I decided to remove as below:-
conda remove pymc3, m2w64 packages. Cold restart.

2) Bleeding-edge theano installation

```
(root) c:/users/franc> pip install --upgrade --no-deps git+git://github.com/Theano/Theano.git

Pip removed previous clone 0.9.0dev4 pkg and re-installed 0.9.0dev4 
    no paths or links made
package installed in c:/anacond3/Lib/site-packages/theano
scripts theano-cache, -nose, -clear installed in c:/anaconda3/scripts
```

Started spyder:
IP[1] import theano
error theano module not found

added c:\anaconda3\Lib\site-packages\theano to PYTHONPATH using environment manager within spyder with success.
It didn't make any change to import theano.

The /lib/site-packages/theano folder has
     _init_.py, setup.py, theano.pyproj, theano.sln, configdefaults.py, configparser.py

I thought the changed path and cold-restart that theano path should have been fixed, but no.
Still theano module not found error.
Looking at sys and os environment variables

os.environ.get('PATH')
Out[13]: 'C:\Anaconda3\Library\bin;C:\Anaconda3\Library\bin;C:\Anaconda3;C:\Anaconda3\Library\mingw-w64\bin;C:\Anaconda3\Scripts;C:\Anaconda3\Library\bin;C:\Anaconda3\Library\bin;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\ProgramData\Oracle\Java\javapath;C:\Program Files\Common Files\Microsoft Shared\Windows Live;C:\Program Files (x86)\Common Files\Microsoft Shared\Windows Live;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\Program Files\WIDCOMM\Bluetooth Software\;C:\Program Files\WIDCOMM\Bluetooth Software\syswow64;C:\Program Files (x86)\Windows Live\Shared;C:\Program Files (x86)\Windows Kits\8.1\Windows Performance Toolkit\;C:\Anaconda3;C:\Anaconda3\Scripts;C:\Anaconda3\Library\bin;C:\Users\Franc\AppData\Local\Enthought\Canopy\User;C:\Users\Franc\AppData\Local\Enthought\Canopy\User\Scripts;C:\Users\Franc\AppData\Local\Microsoft\WindowsApps;C:\Anaconda3\Lib\site-packages\Theano'

Needs tidy up! Enthought folder doesn't exist (can't see),
 too many   c:/anaconda3/library/bin
Don't know how to clean up --> set path = %path%
 under cmd window once I find the syntax.

Can't fix the thenao not found error.
Help would be appreciated.
Please outline what would have been a better approach to install

> bleeding-edge Theano,
> then
> m2w64-toolchain (using conda)
>  then
> bleeding-edge pymc3
> many thanks for our assistance
> frank

**Comment by twiecki** [comment]
You're on Windows and Python 3.5, which seems incompatible with the Theano development version. You can either wait for them to fix it and release updated binaries or use Python 3.4 (anaconda should make it easy to create a conda env with that).

**Comment by unkufunku** [comment]
@twiecki Thank you. It's taken some time without success. I'll follow your advice.
regards frank

**Comment by nouiz** [comment]
For python 3.5, we have a PR that should make that work:

https://github.com/Theano/Theano/pulls/

It is not ready to use.

@notoraptor should start working on the dtype problem this week.

**Comment by twiecki** [comment]
Thanks @nouiz. When do you think a new theano release is happening?

**Comment by nouiz** [comment]
We push for this, but no timeline!

**Comment by twiecki** [comment]
Closed via #1550.

**Comment by napsternxg** [comment]
Hi everyone,

Thanks for the update on the issue. However, I tried the latest pymc3 and theano install (using their git-repos) but am still seeing the following errors:

```

---------------------------------------------------------------------------
InvalidValueError                         Traceback (most recent call last)
<ipython-input-8-3a4f2e83047f> in <module>()
      1 with disaster_model:
----> 2     step1 = pm.NUTS([early_rate, late_rate])
      3 
      4     # Use Metropolis for switchpoint, and missing values since it accommodates discrete variables
      5     step2 = pm.Metropolis([switchpoint, disasters.missing_values[0]] )

E:\Anaconda\lib\site-packages\pymc3\step_methods\nuts.pyc in __init__(self, vars, scaling, step_scale, is_cov, state, Emax, target_accept, gamma, k, t0, model, profile, **kwargs)
     70         if isinstance(scaling, dict):
     71             scaling = guess_scaling(
---> 72                 Point(scaling, model=model), model=model, vars=vars)
     73 
     74         n = scaling.shape[0]

E:\Anaconda\lib\site-packages\pymc3\tuning\scaling.pyc in guess_scaling(point, vars, model, scaling_bound)
    109     model = modelcontext(model)
    110     try:
--> 111         h = find_hessian_diag(point, vars, model=model)
    112     except NotImplementedError:
    113         h = fixed_hessian(point, vars, model=model)

E:\Anaconda\lib\site-packages\pymc3\tuning\scaling.pyc in find_hessian_diag(point, vars, model)
    102     """
    103     model = modelcontext(model)
--> 104     H = model.fastfn(hessian_diag(model.logpt, vars))
    105     return H(Point(point, model=model))
    106 

E:\Anaconda\lib\site-packages\pymc3\memoize.pyc in memoizer(*args, **kwargs)
     13 
     14         if key not in cache:
---> 15             cache[key] = obj(*args, **kwargs)
     16 
     17         return cache[key]

E:\Anaconda\lib\site-packages\pymc3\theanof.pyc in hessian_diag(f, vars)
    107 
    108     if vars:
--> 109         return -tt.concatenate([hessian_diag1(f, v) for v in vars], axis=0)
    110     else:
    111         return empty_gradient

E:\Anaconda\lib\site-packages\pymc3\theanof.pyc in hessian_diag1(f, v)
     98         return gradient1(g[i], v)[i]
     99 
--> 100     return theano.map(hess_ii, idx)[0]
    101 
    102 

E:\Anaconda\lib\site-packages\theano\scan_module\scan_views.pyc in map(fn, sequences, non_sequences, truncate_gradient, go_backwards, mode, name)
     68                      go_backwards=go_backwards,
     69                      mode=mode,
---> 70                      name=name)
     71 
     72 

E:\Anaconda\lib\site-packages\theano\scan_module\scan.pyc in scan(fn, sequences, outputs_info, non_sequences, n_steps, truncate_gradient, go_backwards, mode, name, profile, allow_gc, strict)
   1064             pass
   1065         scan_inputs += [arg]
-> 1066     scan_outs = local_op(*scan_inputs)
   1067     if type(scan_outs) not in (list, tuple):
   1068         scan_outs = [scan_outs]

E:\Anaconda\lib\site-packages\theano\gof\op.pyc in __call__(self, *inputs, **kwargs)
    661                 thunk.outputs = [storage_map[v] for v in node.outputs]
    662 
--> 663                 required = thunk()
    664                 assert not required  # We provided all inputs
    665 

E:\Anaconda\lib\site-packages\theano\scan_module\scan_op.pyc in rval(p, i, o, n, allow_gc)
    951         def rval(p=p, i=node_input_storage, o=node_output_storage, n=node,
    952                  allow_gc=allow_gc):
--> 953             r = p(n, [x[0] for x in i], o)
    954             for o in node.outputs:
    955                 compute_map[o][0] = True

E:\Anaconda\lib\site-packages\theano\scan_module\scan_op.pyc in p(node, args, outs)
    940                                                 args,
    941                                                 outs,
--> 942                                                 self, node)
    943         except (ImportError, theano.gof.cmodule.MissingGXX):
    944             p = self.execute

theano/scan_module/scan_perform.pyx in theano.scan_module.scan_perform.perform (C:\Users\Shubhanshu\AppData\Local\Theano\compiledir_Windows-10-10.0.14393-Intel64_Family_6_Model_58_Stepping_9_GenuineIntel-2.7.12-64\scan_perform\mod.cpp:4415)()

theano/scan_module/scan_perform.pyx in theano.scan_module.scan_perform.perform (C:\Users\Shubhanshu\AppData\Local\Theano\compiledir_Windows-10-10.0.14393-Intel64_Family_6_Model_58_Stepping_9_GenuineIntel-2.7.12-64\scan_perform\mod.cpp:4199)()

E:\Anaconda\lib\site-packages\theano\compile\debugmode.pyc in deco()
   2303                     self.maker.mode.check_isfinite
   2304                 try:
-> 2305                     return f()
   2306                 finally:
   2307                     # put back the filter_checks_isfinite

E:\Anaconda\lib\site-packages\theano\compile\debugmode.pyc in f()
   1960                                 r, storage_map[r][0],
   1961                                 hint=("Graph Input '%s' has invalid value "
-> 1962                                       "%s" % (r, storage_map[r][0])))
   1963                         r_vals[r] = storage_map[r][0]
   1964                         storage_map[r][0] = None

InvalidValueError: InvalidValueError
        type(variable) = TensorType(float32, scalar)
        variable       = TensorConstant{-inf}
        type(value)    = <type 'numpy.ndarray'>
        dtype(value)   = float32
        shape(value)   = ()
        value          = -inf
        min(value)     = -inf
        max(value)     = -inf
        isfinite       = False
        client_node    = None
        hint           = Graph Input 'TensorConstant{-inf}' has invalid value -inf
        specific_hint  = none
        context        = ...
  TensorConstant{-inf} [id A]
```

My notebook is available at: https://github.com/napsternxg/ipython-notebooks/blob/master/PyMC%20Disaster.ipynb

**Comment by twiecki** [comment]
This is a different error, can you open a new issue for that including versions and platform information? Is that the vanilla disaster model?

**Comment by nouiz** [comment]
I think you run Theano in debug mode. By default it raises error for inf
and nan. Check Theano flags to don't have it raises error in that case.

**Comment by twiecki** [comment]
Ah, that makes sense, those flags are set in the code he posted. Thanks for chiming in @nouiz.

**Comment by mullachv** [comment]
I am getting a similar error in Python3 on my Mac

Using the following versions:
```
3.6.0 |Anaconda custom (x86_64)| (default, Dec 23 2016, 13:19:00) 
[GCC 4.2.1 Compatible Apple LLVM 6.0 (clang-600.0.57)]
sys.version_info(major=3, minor=6, micro=0, releaselevel='final', serial=0)
0.9.0.dev-c697eeab84e5b8a74908da654b66ec9eca4f1291
pymc3:  3.0
```
Here is the notebook:
https://github.com/mullachv/MLExp/blob/dirichlet/sampling_err.ipynb

Based on the error, this is not the original error reported by @napsternxg, but his most recent error. So, opening a new issue: #2845
